version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    container_name: app
    image: app
    build: .
    restart: always
    env_file:
      - .env
    command: bash -c "/wait && npm start"
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
    ports:
      - "1337:1337"

volumes:
  pgdata:
