version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15.0-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    container_name: app
    image: app
    build: .
    restart: always
    env_file:
      - .env
    command: sh -c "npm run develop"
    depends_on:
      - postgres
    ports:
      - "1337:1337"
    volumes:
      - src:/app/src/
      - dist:/app/dist/

volumes:
  pgdata:
  src:
  dist:
