name: remote ssh command
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /usr/local/map-admin
          make all
