on:
  push:
    branches:
    - sync

jobs:
  pull-request:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"